name: "AI Code Reviewer"
description: "AI-powered review on every PR"
author: "TusharRoy23"

inputs:
  trigger-phrase:
    description: "Keyword to trigger AI review"
    default: "@ai-code-reviewer review"

  model:
    description: "LLM model"
    default: "gpt-4o-mini"

  openai-api-key:
    description: "OpenAI API key"
    required: true

  max-diff-kb:
    description: "Max diff size in KB"
    default: "150"

  min-severity:
    description: "Minimum severity to report (low, medium, high, critical)"
    default: "medium"

  review-mode:
    description: "Review mode: 'full' (entire PR) or 'incremental' (latest commit only)"
    default: "incremental"

runs:
  using: "composite"
  steps:
    # ------------------------------------------------------
    # 1. VALIDATION & SETUP
    # ------------------------------------------------------
    - name: Check trigger conditions
      id: check
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" != "pull_request" ]] && \
           [[ ! "${{ github.event.comment.body }}" =~ "${{ inputs.trigger-phrase }}" ]]; then
          echo "skip=true" >> $GITHUB_OUTPUT
          echo "Skipping: Not triggered by PR or trigger phrase"
        else
          echo "skip=false" >> $GITHUB_OUTPUT
          echo "Conditions met, proceeding with review"
        fi

    - name: Checkout code
      if: steps.check.outputs.skip != 'true'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Need full history for incremental mode

    - name: Setup Node.js
      if: steps.check.outputs.skip != 'true'
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install pnpm
      if: steps.check.outputs.skip != 'true'
      shell: bash
      run: npm install -g pnpm

    - name: Install dependencies
      if: steps.check.outputs.skip != 'true'
      shell: bash
      run: pnpm install

    - name: Build TypeScript
      if: steps.check.outputs.skip != 'true' && hashFiles('tsconfig.json') != ''
      shell: bash
      run: pnpm run build

    # ------------------------------------------------------
    # 2. DOWNLOAD DIFF (Full or Incremental)
    # ------------------------------------------------------
    - name: Download PR diff
      if: steps.check.outputs.skip != 'true'
      id: diff
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        REVIEW_MODE: ${{ inputs.review-mode }}
      run: |
        PR_NUM="${{ github.event.pull_request.number }}"
        if [ -z "$PR_NUM" ] || [ "$PR_NUM" = "null" ]; then
          PR_NUM="${{ github.event.issue.number }}"
        fi

        echo "PR Number: $PR_NUM"
        echo "Review Mode: $REVIEW_MODE"

        if [ "$REVIEW_MODE" = "incremental" ]; then
          echo "Incremental mode: Reviewing only the latest commit"
          
          # Get the latest commit SHA
          LATEST_COMMIT="${{ github.event.pull_request.head.sha }}"
          echo "Latest commit: $LATEST_COMMIT"
          
          # Get the previous commit (parent)
          if PREVIOUS_COMMIT=$(git rev-parse ${LATEST_COMMIT}^ 2>/dev/null); then
            echo "Previous commit: $PREVIOUS_COMMIT"
            # Generate diff for just the latest commit
            git diff $PREVIOUS_COMMIT $LATEST_COMMIT > pr.diff
          else
            echo "Could not find parent commit (might be first commit)"
            echo "Falling back to compare with base branch"
            # First commit in branch, compare with base
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            git diff $BASE_SHA $LATEST_COMMIT > pr.diff
          fi
          
          echo "Generated diff for latest commit only"
          
        else
          echo "Full mode: Reviewing entire PR"
          
          # Download full PR diff from GitHub API
          curl -sL \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3.diff" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUM" \
            > pr.diff
          
          echo "Downloaded full PR diff"
        fi

        SIZE=$(du -k pr.diff | cut -f1)
        echo "Diff size: ${SIZE} KB"

        if [ "$SIZE" -gt "${{ inputs.max-diff-kb }}" ]; then
          echo "Diff too large (${SIZE} KB > ${{ inputs.max-diff-kb }} KB). Skipping review."
          echo "large_diff=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        if [ "$SIZE" -eq 0 ]; then
          echo "Diff is empty (0 KB). Skipping review."
          echo "large_diff=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "large_diff=false" >> $GITHUB_OUTPUT

    - name: Filter meaningful code changes
      if: steps.check.outputs.skip != 'true' && steps.diff.outputs.large_diff != 'true'
      shell: bash
      run: |
        echo "Filtering diff for meaningful code changes..."

        ALLOWED_EXTENSIONS="(ts|tsx|js|jsx|py|java|go|cpp|c|rb|php|swift|rs|kt|scala|cs|html|css|scss|vue|svelte)"

        awk -v EXT="$ALLOWED_EXTENSIONS" '
          BEGIN { keep = 0; }

          /^diff --git / {
            match($0, / a\/([^ ]+) b\//, m);
            file=m[1];
            keep=0;

            # Include files with allowed extensions
            if (file ~ ("\\." EXT "$")) keep=1;

            # Exclude specific files
            if (file ~ /(^|\/)(package(-lock)?\.json)$/) keep=0;
            if (file ~ /(^|\/)pnpm-lock\.yaml$/) keep=0;
            if (file ~ /(^|\/)yarn\.lock$/) keep=0;
            if (file ~ /(^|\/)tsconfig.*\.json$/) keep=0;
            if (file ~ /(^|\/)\.(gitignore|gitattributes|editorconfig)$/) keep=0;
            if (file ~ /\.(md|txt|csv)$/) keep=0;
            if (file ~ /\.min\.(js|css)$/) keep=0;
            if (file ~ /\.map$/) keep=0;

            if (!keep) {
              printf "Skipping %s\n", file > "/dev/stderr";
            }
          }

          { if (keep) print; }
        ' pr.diff > pr.filtered.diff

        echo "Filtering complete"

    - name: Show files being reviewed
      if: steps.check.outputs.skip != 'true' && steps.diff.outputs.large_diff != 'true'
      shell: bash
      run: |
        FILE_COUNT=$(grep -c "^diff --git" pr.filtered.diff 2>/dev/null || echo "0")
        echo "Files being reviewed: $FILE_COUNT"

        if [ "$FILE_COUNT" -gt 0 ]; then
          awk '/^diff --git / { 
            match($0, / b\/(.+)$/, m); 
            if (m[1]) print "  - " m[1]; 
          }' pr.filtered.diff
        fi

    - name: Detect project info
      if: steps.check.outputs.skip != 'true'
      id: projectinfo
      shell: bash
      run: |
        echo "ðŸ” Detecting project information..."

        # Run the detector script
        INFO=$(node ${{ github.action_path }}/scripts/project-info-detector.js)

        # Check if INFO is valid JSON
        if ! echo "$INFO" | jq empty 2>/dev/null; then
          echo "Failed to detect project info, using defaults"
          echo "LANGUAGES=Unknown" >> $GITHUB_ENV
          echo "FRAMEWORKS=Unknown" >> $GITHUB_ENV
          echo "LIBRARIES=Unknown" >> $GITHUB_ENV
          echo "PROJECT_TYPE=general" >> $GITHUB_ENV
        else
          # Parse JSON and set env variables
          LANGS=$(echo "$INFO" | jq -r '.languages | join(",")')
          FRAMES=$(echo "$INFO" | jq -r '.frameworks | join(",")')
          LIBS=$(echo "$INFO" | jq -r '.libraries | join(",")')
          TYPE=$(echo "$INFO" | jq -r '.projectType')
          
          # Handle empty arrays
          if [ -z "$LANGS" ] || [ "$LANGS" = "null" ]; then
            LANGS="Unknown"
          fi
          if [ -z "$FRAMES" ] || [ "$FRAMES" = "null" ]; then
            FRAMES="None"
          fi
          if [ -z "$LIBS" ] || [ "$LIBS" = "null" ]; then
            LIBS="None"
          fi
          if [ -z "$TYPE" ] || [ "$TYPE" = "null" ]; then
            TYPE="general"
          fi
          
          echo "LANGUAGES=$LANGS" >> $GITHUB_ENV
          echo "FRAMEWORKS=$FRAMES" >> $GITHUB_ENV
          echo "LIBRARIES=$LIBS" >> $GITHUB_ENV
          echo "PROJECT_TYPE=$TYPE" >> $GITHUB_ENV
          
          echo "   Detected:"
          echo "   Languages: $LANGS"
          echo "   Frameworks: $FRAMES"
          echo "   Libraries: $LIBS"
          echo "   Type: $TYPE"
        fi

    # ------------------------------------------------------
    # 3. RUN AI REVIEW
    # ------------------------------------------------------
    - name: Run AI Code Review
      if: |
        steps.check.outputs.skip != 'true' && 
        steps.diff.outputs.large_diff != 'true'
      id: review
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        MODEL: ${{ inputs.model }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_REF: ${{ github.ref }}
        MIN_SEVERITY: ${{ inputs.min-severity }}
        LANGUAGES: ${{ env.LANGUAGES }}
        FRAMEWORKS: ${{ env.FRAMEWORKS }}
        LIBRARIES: ${{ env.LIBRARIES }}
        PROJECT_TYPE: ${{ env.PROJECT_TYPE }}
      run: |
        if [ ! -s pr.filtered.diff ]; then
          echo "No meaningful code changes found. Skipping AI review."
          echo "has_changes=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "   Running AI code review..."
        echo "   Model: $MODEL"
        echo "   Languages: $LANGUAGES"
        echo "   Frameworks: $FRAMEWORKS"
        echo "   Libraries: $LIBRARIES"
        echo "   Project Type: $PROJECT_TYPE"
        echo "   GITHUB_SHA: $GITHUB_SHA"
        echo "   GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
        echo "   GITHUB_REF: $GITHUB_REF"
        echo "   "

        # Run review with tee to see output
        if node ${{ github.action_path }}/scripts/review-bot.js pr.filtered.diff > review.md; then
          echo ""
          echo "AI review completed successfully"
          
          # Show statistics
          if [ -f review.md ]; then
            SIZE=$(wc -c < review.md)
            LINES=$(wc -l < review.md)
            echo "Generated review: $SIZE bytes, $LINES lines"
            cat review.md
            # Validate JSON
            if cat review.md | jq empty 2>/dev/null; then
              CHUNKS=$(cat review.md | jq 'length')
              echo "Review chunks: $CHUNKS"
            else
              echo "Output is not valid JSON"
            fi
          fi
          
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "AI review failed"
          exit 1
        fi

    # ------------------------------------------------------
    # 4. POST REVIEW COMMENTS
    # ------------------------------------------------------
    - name: Post review comments
      if: |
        steps.check.outputs.skip != 'true' &&
        steps.review.outputs.has_changes == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        REVIEW_MODE: ${{ inputs.review-mode }}
      run: |
        echo "Posting review comments to PR..."

        if [ "$REVIEW_MODE" = "incremental" ]; then
          echo "Mode: Incremental (latest commit only)"
        else
          echo "Mode: Full PR review"
        fi

        node ${{ github.action_path }}/scripts/post-review.js review.md

    # ------------------------------------------------------
    # 5. CLEANUP
    # ------------------------------------------------------
    - name: Cleanup
      if: always()
      shell: bash
      run: |
        echo "Cleaning up temporary files..."
        rm -f pr.diff pr.filtered.diff alldiff.tmp review.md
        echo "Cleanup complete"
