name: "AI Code Reviewer"
description: "AI-powered review on every PR"
author: "TusharRoy23"

inputs:
  trigger-phrase:
    description: "Keyword to trigger AI review"
    default: "@ai-code-reviewer review"

  model:
    description: "LLM model"
    default: "gpt-4o-mini"

  openai-api-key:
    description: "OpenAI API key"

  max-diff-kb:
    description: "Max diff size in KB"
    default: "50"

runs:
  using: "composite"
  steps:
    - name: Skip if not relevant
      if: >-
        github.event_name != 'pull_request' &&
        !contains(github.event.comment.body, inputs.trigger-phrase)
      shell: bash
      run: exit 0

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install pnpm
      shell: bash
      run: npm install -g pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Build (TypeScript)
      if: hashFiles('tsconfig.json') != ''
      shell: bash
      run: pnpm run build

    # ------------------------------------------------------
    # DOWNLOAD PR DIFF
    # ------------------------------------------------------
    - name: Download PR diff
      id: diff
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        PR_NUM="${{ github.event.pull_request.number }}"
        if [ -z "$PR_NUM" ] || [ "$PR_NUM" = "null" ]; then
          PR_NUM="${{ github.event.issue.number }}"
        fi

        curl -sL \
          -H "Authorization: token $GH_TOKEN" \
          -H "Accept: application/vnd.github.v3.diff" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUM" \
          > pr.diff

        SIZE=$(du -k pr.diff | cut -f1)
        if [ "$SIZE" -gt "${{ inputs.max-diff-kb }}" ]; then
          echo "Diff too large ($SIZE KB). Skipping."
          exit 0
        fi

    # ------------------------------------------------------
    # FILTER DIFF — KEEP ONLY REAL CODE FILES
    # ------------------------------------------------------
    - name: Filter meaningful code changes
      shell: bash
      run: |
        echo "Filtering diff..."

        ALLOWED_EXTENSIONS="(ts|tsx|js|jsx|py|java|go|cpp|c|rb|php|swift|rs|kt|scala|cs|html|css|scss|vue|svelte)"

        awk '{ print }' pr.diff > alldiff.tmp

        awk -v EXT="$ALLOWED_EXTENSIONS" '
          BEGIN { keep = 0; }

          /^diff --git / {
            match($0, / a\/([^ ]+) b\//, m);
            file=m[1];
            keep=0;

            if (file ~ ("\\." EXT "$")) keep=1;

            if (file ~ /(^|\/)(package(-lock)?\.json)$/) keep=0;
            if (file ~ /(^|\/)pnpm-lock\.yaml$/) keep=0;
            if (file ~ /(^|\/)yarn\.lock$/) keep=0;
            if (file ~ /(^|\/)tsconfig.*\.json$/) keep=0;
            if (file ~ /(^|\/)\.(gitignore|gitattributes|editorconfig)$/) keep=0;

            if (file ~ /\.(md|txt|csv)$/) keep=0;

            if (!keep) {
              printf "Skipping %s\n", file > "/dev/stderr";
            }
          }

          { if (keep) print; }
        ' alldiff.tmp > pr.filtered.diff

        rm alldiff.tmp

        echo "Filtered diff preview:"

    - name: Show files passing filter
      shell: bash
      run: |
        echo "Files being reviewed:"
        # Extract filenames from pr.filtered.diff
        awk '/^diff --git / { match($0, / b\/(.+)$/, m); if (m[1]) print m[1]; }' pr.filtered.diff

    # ------------------------------------------------------
    # RUN AI REVIEW
    # ------------------------------------------------------
    - name: Run AI Code Review
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        MODEL: ${{ inputs.model }}
      run: |
        if [ ! -s pr.filtered.diff ]; then
          echo "No meaningful code changes. Skipping AI review."
          exit 0
        fi

        node ${{ github.action_path }}/review-bot.js pr.filtered.diff > review.md || exit 1

    - name: Post AI Code Review
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const raw = fs.readFileSync('review.md', 'utf8').trim();
          if (!raw) {
            console.log("No review generated.");
            return;
          }

          let reviews;
          try {
            reviews = JSON.parse(raw);
          } catch (e) {
            console.log("Invalid JSON, falling back to raw text");
            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## AI Code Review\n\n${raw}\n\nReviewed with ${process.env.MODEL || 'GPT-4o'}`
            });
            return;
          }

          const prNumber = context.payload.pull_request.number;

          // ── 1. Post inline comments (one per issue) ─────────────────────
          for (const file of reviews) {
            const filename = file.filename;

            for (const category of file.issues || []) {
              const type = category.type.toUpperCase();
              const issueList = category.issues.flat(); // flatten nested arrays

              for (const issue of issueList) {
                if (!issue || !issue.description) continue;

                const severityEmoji = {
                  critical: "Critical",
                  high: "High",
                  medium: "Medium",
                  low: "Low"
                }[issue.severity] || "Info";

                const body = `**${type} • ${severityEmoji} ${issue.severity.toUpperCase()}**\n\n` +
                             `${issue.description}\n\n` +
                             (issue.recommendation ? `**Fix:** ${issue.recommendation}\n` : "") +
                             (issue.lineStart ? `\nLines ${issue.lineStart}${issue.lineEnd && issue.lineEnd !== issue.lineStart ? `-${issue.lineEnd}` : ""}` : "");

                // Post inline comment
                await github.rest.pulls.createReviewComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: prNumber,
                  path: filename,
                  body: body,
                  line: issue.lineStart || 1,
                  side: "RIGHT"
                });
              }
            }
          }

          // ── 2. Post summary comment (one per PR) ────────────────────────
          const totalIssues = reviews.reduce((sum, f) => 
            sum + (f.issues || []).reduce((s, c) => 
              s + (c.issues?.flat().length || 0), 0), 0);

          const highCritical = reviews.flatMap(f => f.issues || [])
            .flatMap(c => c.issues?.flat() || [])
            .filter(i => i.severity === "high" || i.severity === "critical").length;

          const summaryEmoji = highCritical > 0 ? "Warning" : (totalIssues > 0 ? "Warning" : "Success");

          const summary = `## AI Code Review Complete\n\n` +
                          `${summaryEmoji} **${totalIssues} issue${totalIssues !== 1 ? 's' : ''} found** ` +
                          `${highCritical > 0 ? `• ${highCritical} high/critical` : ''}\n\n` +
                          `Reviewed ${reviews.length} file${reviews.length !== 1 ? 's' : ''} ` +
                          `using **${process.env.MODEL || 'GPT-4o'}**\n\n` +
                          `_7 expert agents: security • correctness • performance • testing • readability • idiomatic • architecture_`;

          await github.rest.issues.createComment({
            issue_number: prNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: summary
          });
